#!/usr/bin/env bash
# Script that handles SIGTERM gracefully and runs forever, printing a phrase every 2 seconds

trap 'echo "I am invincible!!!"' SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
