#!/usr/bin/env bash
# china japan italy

i=1

while [ $i -lt 21 ]; do
	case $i in 
	4)
	echo "bad luck from china"
	;;
	9)
	echo "bad luck from japan"
	;;
	17)
	echo "bad luck from italy"
	;;
	*)
	
	echo "$i"
	;;
	esac
	((i++))
done
